apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: welcome-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: homelab-t480s.tailb18fbd.ts.net
      http:
        paths:
          - path: /welcome(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: welcome-service
                port:
                  number: 80
