apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Create PVCs FIRST (before PVs with claimRef)
  - sonarr-config-pvc.yaml
  - radarr-config-pvc.yaml
  - prowlarr-config-pvc.yaml
  - qbittorrent-config-pvc.yaml
  - tv-pvc.yaml
  - movies-pvc.yaml
  - downloads-pvc.yaml
  # Then create PVs (with claimRef pointing to existing PVCs)
  - sonarr-config-pv.yaml
  - radarr-config-pv.yaml
  - prowlarr-config-pv.yaml
  - qbittorrent-config-pv.yaml
  - tv-pv.yaml
  - movies-pv.yaml
  - downloads-pv.yaml
