apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
spec:
  storageClassName: "local-storage"
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ops/media-stack/config/qbittorrent"
  claimRef:
    name: qbittorrent-config-pvc
    namespace: default

