apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
    - host: homelab-t480s.tailb18fbd.ts.net
      http:
        paths:
          - path: /media/qbittorrent
            pathType: Prefix
            backend:
              service:
                name: qbittorrent
                port:
                  number: 8081

