apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-api-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: homelab-t480s.tailb18fbd.ts.net
      http:
        paths:
          - path: /media/qbittorrent/api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: qbittorrent
                port:
                  number: 8081

