apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: default
  labels:
    app: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8090
      name: webui
    - protocol: TCP
      port: 6881
      targetPort: 6881
      name: torrent-tcp
    - protocol: UDP
      port: 6881
      targetPort: 6881
      name: torrent-udp
  type: NodePort

